services:

  limesurvey:
    image: acspri/limesurvey
    ports:
      - 8082:80
    environment:
      LIMESURVEY_DB_PASSWORD: example
      LIMESURVEY_ADMIN_USER: admin
      LIMESURVEY_ADMIN_PASSWORD: password
      LIMESURVEY_ADMIN_NAME: Lime Administrator
      LIMESURVEY_ADMIN_EMAIL: admin@admin.com
      LIMESURVEY_DEBUG: 2
    volumes:
      - ./limesurvey/plugins:/var/www/html/plugins
      - ./limesurvey/upload:/var/www/html/upload
      - ./limesurvey/config:/var/www/html/application/config

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
